export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const ADD_GAME_SUCCESS = "ADD_GAME_SUCCESS";
export const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";
export const DELETE_GAME = "DELETE_GAME";
export const LOAD_DEVELOPERS_SUCCESS = "LOAD_DEVELOPERS_SUCCESS";

export const START_API_CALL = "START_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
